### PR TITLE
Fix windows symlink

### PR DESCRIPTION
**Pull request by operatino**
Aligned symlinking approach with https://github.com/bower/bower/blob/master/lib/util/createLink.js

Fixing #30.

### CODE REVIEW

**Comment by ben-eb** [comment]
Is it possible to unit test this?

**Comment by operatino** [comment]
Only if running tests in Win environment.

**Comment by ben-eb** [comment]
Do you have any experience with appveyor? I've added this repository to it, we could set up a Windows build with it. :smile:

**Comment by operatino** [comment]
Didn't heard about appveyor before, I was testing directly on my virtual box.

**Comment by ben-eb** [comment]
If you could provide a test for Windows then we could run that in the build if `process.platform === 'win32'` :smile:

**Comment by operatino** [comment]
It should be enough to just run the existing tests, since they are failing on Windows. I figured out how to configure AppVeyor, will add config for that in PR.

**Comment by operatino** [comment]
Ok, so now it fails because of mocha, could you check it?

**Comment by ben-eb** [comment]
Yeah, the dev dependencies haven't been bumped in a while, sorry. :smiley:

**Comment by operatino** [comment]
Now it works :)

**Comment by ben-eb** [comment]
Great! Could you please squash your commits? I'll get this merged when I get back this evening. :smile:

http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by operatino** [comment]
Done. I decided to left these 3.

**Comment by ben-eb** [comment]
Great stuff, thanks.

**Pull request merged**
